spring:
  profiles:
    active: production
line.bot:
  #cron: 05 * * * * ?
  cron: 10 */60 * * * ?
  channel-token: ''
  channel-secret: ''
  handler.path: /callback
---
spring:
  profiles: production
  influxdb:
        enable: true
        url: http://192.168.1.1:8086
        username: admin
        password: admin
        database: LINE_KAWASE
        retention-policy: autogen
        fakedata: false
        jpyrate: false
# http server port
server:
  port: 19901

---
spring:
  profiles: develop
  influxdb:
        enable: true
        url: http://127.0.0.1:8086
        username: admin
        password: admin
        database: LINE_KAWASE
        retention-policy: autogen
        fakedata: false
        jpyrate: false
# http server port
server:
  port: 19901
