spring:
  profiles:
    active: development

---

spring:
  profiles: production

---
spring:
  profiles: production-amazon

maildeliver:
  host: smtp.gmail.com
  port: 587
  username: name
  password: password
---
spring:
  profiles: development

maildeliver:
  host: smtp.gmail.com
  port: 587
  username: name
  password: password
---
spring:
  profiles: development-i7

maildeliver:
  host: smtp.gmail.com
  port: 587
  username: name
  password: password
---
