spring:
  profiles:
    active: development

---
spring:
  profiles: production

maildeliver:
  host: smtp.gmail.com
  port: 587
  username: name
  password: password
---
spring:
  profiles: development

maildeliver:
  host: smtp.gmail.com
  port: 587
  username: name
  password: password
---

