spring:
  profiles:
    active: production

---
spring:
  profiles: production

database.influxdb:
      enable: true
      url: http://localhost:8086
      username: admin
      password: admin
      database: SYSTEM
      retention-policy: autogen
      fakedata: false
      jpyrate: true
# http server port
server:
  port: 8080

---
